### ISSUE TITLE
Can we customize the Drag Preview ?

### ISSUE THREAD

**Issue by yogeshtiwari1990** [frontend-collective/react-sortable-tree#188]
Currently the Drag Preview includes node with its children. 
In some conditions we want to only show the node not its children.

Drag Hover is not an issue because it has only the node being dragged.

Is it possible to do?
If not, please point me in right direction.

**Comment by fritz-c** [comment]
You’d have to use a customNodeRenderer, and adjust the location of the `connectDragPreview` call.
