### ISSUE TITLE
Parent/Child rendered doesn't work

### ISSUE THREAD

**Issue by varjodesign** [frontend-collective/react-sortable-tree#193]
Hi!
I've installed latest package via npm to my project and copy pasted treedata/treeimport source but it just doesn't work. My project doesnt recognize keyword 'node' and cant find functions   getFlatDataFromTree and   getTreeFromFlatData from source. My IDE just paints words like 'flatdata' and 'getnodekey' to grey and cant use 'em.

EDIT:
So i was in hurry. So basically i have this db where is all my data with parents, names, id:s and so on. When component mounts function grabs all the data from db and pushes 'em to array with right values. Problem comes when it should show which is which parent and render the tree. It just doesn't work. I pasted treedata/treeimport code also to my projectfile but it didn't work neither.

**Comment by lifejuggler** [comment]
I don't think you have built the correct data to put into the treeData prop...

**Comment by varjodesign** [comment]
Hi! All the data is in the right place. Data will be added when component mounts. But when i think about it does parent prop act like child? Does it render cells under eachothers in right places?

**Comment by lifejuggler** [comment]
I don't quite understand your wordings but are you asking if it does the correct rendering? :S
