### ISSUE TITLE
Does the component support direction changing?

### ISSUE THREAD

**Issue by SomoKRoceS** [frontend-collective/react-sortable-tree#209]
Hey,
I would like to use the component with an opposite direction (right to left).
Does the component support direction changing?

Thanks.

**Comment by jzoric** [comment]
Hi,
it doesn't support direction changing. Maybe you can achieve this by creating a custom theme?

**Comment by buzztone** [comment]
I'm wondering if this likely to be common requirement for applications supporting RTL langauges.

**Comment by SomoKRoceS** [comment]
jzoric, 
Yea.. I guess a custom theme is the only way.

buzztone, 
Well.. I suppose it is. Components in applications supporting RTL languages are mostly preferred to be RTL (some might be a "must"), However, there are some application components or requirements that LTR could fit as well.
A vertical tree, for example, with LTR-ordered nodes that holds RTL text, might be a bit non-intuitive for the user. That's a considerable UX issue.

**Comment by wuweiweiwu** [comment]
Seems to be related to #253

**Comment by olgadr** [comment]
Hi, I've created custom RTL theme, that looks great, the only problem is getTargetDepth function, that calculates the depth by element x offset, any idea how can I overwrite this function?

**Comment by wuweiweiwu** [comment]
@olgadr That'll be tough since we do some tricky css styling around the positioning of the nodes. But possible in the next major release.

**Comment by wuweiweiwu** [comment]
rtl support is merged in #337 🙌 I will release a minor version soon
