### ISSUE TITLE
RTL support?

### ISSUE THREAD

**Issue by Mulli** [frontend-collective/react-sortable-tree#253]
I would like to use RST for a Right to Left language.

Quick view into CSS shows that it will not be an easy task.

Any idea how to proceed?
Am I missing something?

**Comment by fritz-c** [comment]
I'm afraid I don't have any experience with RTL support, so I wouldn't know how to proceed.

**Comment by Mulli** [comment]
The whole idea is kind of a mirror-view which often end up in replacing right & left.
I did try, but gave up when the indentation is computed within the scripts.
Unfortunately I had to give up.

**Comment by wuweiweiwu** [comment]
rtl support is merged in #337 🙌 I will release a minor version soon
