### ISSUE TITLE
Replace deprecated / async-unsafe lifecycles

### ISSUE THREAD

**Issue by wuweiweiwu** [frontend-collective/react-sortable-tree#273]
https://github.com/bvaughn/react-virtualized/pull/1009
https://deploy-preview-596--reactjs.netlify.com/blog/2018/03/15/update-on-async-rendering.html

Migrate to `getDerivedStateFromProps` 

and move off soon to be deprecated lifecycle functions in react 16.x:

`componentWillMount`
`componentWillReceiveProps`
`componentWillUpdate`

**Comment by wuweiweiwu** [comment]
done!

**Comment by TdyP** [comment]
Hi there,
any idea when latest fixes will be released? I'm having warnings on v2.6.2 with React v16.9

```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DragSource(NodeRendererDefault), DropTarget(TreeNode)
```


Thanks!

**Comment by NickEmpetvee** [comment]
@TdyP is this still happening for you? I haven't tried converting my implementation yet to hooks.

**Comment by TdyP** [comment]
> @TdyP is this still happening for you? I haven't tried converting my implementation yet to hooks.

Everything is fine now, problem solved
