### ISSUE TITLE
Rewrite the documentation

### ISSUE THREAD

**Issue by wuweiweiwu** [frontend-collective/react-sortable-tree#282]
I really like how `react-dnd`'s website looks http://react-dnd.github.io/react-dnd/

react-router's website is awesome too! https://reacttraining.com/react-router/web/guides/philosophy

perhaps something with live code examples

- [x] keep storybooks
- [ ] use codesandbox git extractor 
- [x] new website using zeit.co realtime deployments "now.sh"
- [x] new icon
- [ ] better website

**Comment by nickwil** [comment]
I'm more than willing to take on this project. I'll send a pull request your way in the upcoming week

**Comment by wuweiweiwu** [comment]
@nickwil Awesome! I look forward to your PR

**Comment by wuweiweiwu** [comment]
this is nice http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/basic-usage?_k=o1f3s9
