### ISSUE TITLE
Can I implement nested features?

### ISSUE THREAD

**Issue by xgzl87** [frontend-collective/react-sortable-tree#302]
# Requesting a Feature?
case:
I want to implement the function of decomposition relations，
mind:
![default](https://user-images.githubusercontent.com/12945325/39742828-8aa0c7ae-52d1-11e8-8bb9-179d12a16c4d.png)
How to use the existing function nested tree structure?

**Comment by wuweiweiwu** [comment]
I would specify the hierarchal data in `treeData` prop.

**Comment by xgzl87** [comment]
After the update, please  sent a message to inform me about it. Thanks

**Comment by xgzl87** [comment]
Is this feature ready?

**Comment by wuweiweiwu** [comment]
Hi @xgzl87, you have to specify the node hiearchies in the `treeData` prop. I would checkout the example on the main website. 

https://frontend-collective.github.io/react-sortable-tree/
