### ISSUE TITLE
chrom report "uncontrolled input of type undefined to be controlled"

### ISSUE THREAD

**Issue by liuhaif** [frontend-collective/react-sortable-tree#307]
When edit content, chrom report "VM1313 bundle.js:75157 Warning: A component is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components".
The reason is this code: "value={node.name}". 

How can I resolve this question?

Thanks!

The CODE:
<SortableTree
                        treeData={this.state.treeData}
                        onChange={treeData => this.setState({ treeData })}
                        generateNodeProps={({ node, path ,treeIndex }) => ({
                            title: (
                                <input
                                    style={{ fontSize: '1.1rem' }}
                                    value={node.name}
                                    onChange={(event) => this.updateNode( event, node , path , treeIndex)}
                                />
                            ),
                            buttons: [
                                <button label='Delete'
                                        onClick={(event) => this.removeNode( node , path , treeIndex)}>Remove</button>,
                                <button label='add'
                                        onClick={(event) => this.addNode(node , path , treeIndex)}>add</button>,
                            ],
                        })}
                    />

**Comment by wuweiweiwu** [comment]
Hi @liuhaif can you post your code in a working [codesandbox](https://codesandbox.io/)? Thanks

It'll be nice to have a minimum reproduction since I don't know what other parts of your code are doing

**Comment by brenopolanski** [comment]
I fixed it. I just added:

```
...
newNode: {
  ...node,
  title: `${getRandomName()}`,
  name: `${getRandomName()}`
},
...
```

In the `Add Child` button.
