### ISSUE TITLE
RTL drag and drop issue

### ISSUE THREAD

**Issue by olgadr** [frontend-collective/react-sortable-tree#311]
Hi, I've created custom RTL theme, that looks great, the only problem is getTargetDepth function, that calculates the depth by element x offset, any idea how can I overwrite this function?

**Comment by wuweiweiwu** [comment]
#331 Is currently what is in progress. 

Right now I havent taken too much time to look at how the offset is calculated. But I'm thinking that based on a new prop `direction` we can pass that into `getTargetDepth` and adjust the depth calculations accordingly
