### ISSUE TITLE
rtl-support

### ISSUE THREAD

**Issue by lionben89** [frontend-collective/react-sortable-tree#325]
I added rtl-support, i want to share this feature with you,
how can I do it? 

I tried to push my branch to make a pull request without any success, 
please help.

Thanks,
lion

**Comment by RobotnickIsrael** [comment]
Hi.

I would like that too.
Any updates on the issue? Can you help him make a pull request?

**Comment by wuweiweiwu** [comment]
hi @lionben89 I have created it for you! https://github.com/frontend-collective/react-sortable-tree/pull/331

any commits you make to the `ltr-support` branch will update in the PR

**Comment by wuweiweiwu** [comment]
I would recommend rebasing of master to get the most recent changes.

```
git checkout master
git pull master
git checkout ltr-support
git rebase master

# and fix merge conflicts
```
