### ISSUE TITLE
Update react-dnd

### ISSUE THREAD

**Issue by wuweiweiwu** [frontend-collective/react-sortable-tree#336]
Currently we are running 3.0.2, a whole major version behind the most recent 4.0.2.

Might be worth considering doing #335 however, that'll take a bunch of time. This is a short term fix and it should fix a ton of bugs.

**Comment by medslt** [comment]
+ 1

**Comment by marisev** [comment]
any plans on this? :)

**Comment by wuweiweiwu** [comment]
@marisev been a bit busy with work. I'll hopefully be able to take a look this weekend :)

**Comment by wuweiweiwu** [comment]
released in 2.4.0!!
