### ISSUE TITLE
Module not found: Error: Can't resolve 'redux/lib/createStore' in '/dnd-core/lib'

### ISSUE THREAD

**Issue by medslt** [frontend-collective/react-sortable-tree#350]
I'm using "redux": "4.0.0" and the following error occurred when I implemented yarn start to build.

Here is the error message.
`ERROR in ./node_modules/dnd-core/lib/DragDropManager.js
Module not found: Error: Can't resolve 'redux/lib/createStore' in '/Users/moh/sites/wynd/back_office/node_modules/dnd-core/lib'
 @ ./node_modules/dnd-core/lib/DragDropManager.js 9:19-51
 @ ./node_modules/dnd-core/lib/index.js
 @ ./node_modules/react-dnd/lib/DragDropContext.js
 @ ./node_modules/react-dnd/lib/index.js
 @ ./node_modules/react-sortable-tree/dist/main.js
 @ ./app/Resources/modules/Wynd/StoreModelingBundle/components/tree/index.tsx
 @ ./app/Resources/modules/Wynd/StoreModelingBundle/components/StoreModeling.tsx
 @ ./app/Resources/modules/Wynd/StoreModelingBundle/StoreModelingEndPoint.tsx
 @ ./app/Resources/modules/Wynd/StoreModelingBundle/StoreModelingBundle.ts
 @ ./app/Resources/modules/AppKernel.ts
 @ ./app/Resources/modules/app.ts
 @ ./app/Resources/modules/index.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./app/Resources/modules/index.ts`

**Comment by S-Eddine** [comment]
i have the same problem ! :(

**Comment by medslt** [comment]
@lifejuggler I tried it I have the same problem :(

**Comment by lifejuggler** [comment]
@I will take a look and see if I can make a pr

**Comment by lifejuggler** [comment]
@medslt @S-Eddine I have tried to replicate the issue with no success so please provide more information to the steps/ configurations that both of you have tried to get this error...

**Comment by medslt** [comment]
@lifejuggler to replicate the issue you have to use redux 4 in your project, there is a conflict with react-dnd "2.6.0" used by react-sortable-tree, I think  to resolve the issue we have to upgrade react-dnd to the last version

**Comment by S-Eddine** [comment]
@medslt Awesome!! your solution works great!
@lifejuggler that would be nice if we can update the version of react dnd

**Comment by lifejuggler** [comment]
@medslt, cool I will upgrade the version of the react-dnd after I make sure that there are no breaking changes in the latest

**Comment by medslt** [comment]
thanks @lifejuggler
