### ISSUE TITLE
suggestion: create a new project for the next major version release

### ISSUE THREAD

**Issue by lifejuggler** [frontend-collective/react-sortable-tree#353]
Hey @wuweiweiwu, 

I know that you might be very busy, but I would like to help with this project to its next step, whenever I have the time. if you can create a project and add all the requirements maybe I can start picking up some and create a PR for them for you to use to bundle into the next release

**Comment by wuweiweiwu** [comment]
@lifejuggler that'll be awesome. I'll work on some sort of roadmap. In the mean time, I can add you to this organization.

**Comment by wuweiweiwu** [comment]
I have added you as a collaborator on this project!
