### ISSUE TITLE
Cannot read property 'getMonitor' of undefined

### ISSUE THREAD

**Issue by slemvs** [frontend-collective/react-sortable-tree#363]
Hi, 
Could you help me with this problem, please?
I try to use SortableTree with touch support. I copied code sample (touch-support) from storybook app and when i try to use this:
```
import { SortableTreeWithoutDndContext as SortableTree } from "react-sortable-tree";
``` 
instead of this
```
import SortableTree from "react-sortable-tree";
```
I got error:
![image](https://user-images.githubusercontent.com/17675314/42018314-eaed0078-7adb-11e8-9474-50e26371db28.png)

I have prepared a code sample to reproduce the error
https://codesandbox.io/s/ov1n19x0r5

**Comment by slemvs** [comment]
Sample from your sandbox https://codesandbox.io/s/1r3vz5mmyj from this [page](https://frontend-collective.github.io/react-sortable-tree/?selectedKind=Advanced&selectedStory=Touch%20support%20%28Experimental%29&full=0&addons=0&stories=1&panelRight=0) is not working too. Error the same.

**Comment by slemvs** [comment]
It seems that the problem is related to the version of react-dnd library. If you use the version 3.0.2 it works!
But if you switch to the latest 5.0.1 version you receive an error as above.

**Comment by wuweiweiwu** [comment]
so many react dnd bugs #336 .... :(

**Comment by lifejuggler** [comment]
@slemvs , @wuweiweiwu  I attempted an upgrade but the react-dnd is now using the latest this.context which breaks many parts in the code... will try again when I have a solid block of time to resolve this or @wuweiweiwu, I saw your comments that you will take a look?

**Comment by wuweiweiwu** [comment]
@lifejuggler Thanks for taking a look! I was planning on it. But havent had time recently.

**Comment by nyn0x** [comment]
@wuweiweiwu Hello, I try with **SortableTreeWithoutDndContext** like this with DragDropContext (without it, it give me an error 'Cannot read property Monitor of undefined' ) : 
[https://github.com/frontend-collective/react-sortable-tree/blob/97610d1705451e260e4d1f2d587c169709f5a5de/examples/storybooks/external-node.js](https://github.com/frontend-collective/react-sortable-tree/blob/97610d1705451e260e4d1f2d587c169709f5a5de/examples/storybooks/external-node.js)

but he doesn't work.
Here is my demo: https://codesandbox.io/s/8xyln2qvv8

**Comment by votiv** [comment]
Hi! Is there a workaround to this problem until it get's solved?

**Comment by slemvs** [comment]
@votiv Yes, just switch the version of react-dnd from latest to 3.0.2. In my case it helped.

**Comment by slemvs** [comment]
> @slemvs Unfortunately downgrading react-dnd to 3.0.2 did not work... Still same error.

@NoureldeanSaed There is a working example https://codesandbox.io/s/98kj095wwy. Please, check all dependencies versions in it.
