### ISSUE TITLE
Can you make <buttons> inside of generateNodeProps display conditionally?

### ISSUE THREAD

**Issue by NickEmpetvee** [frontend-collective/react-sortable-tree#366]
Hi guys. Suppose we have code like the below. If we always want button 1 to display but only want button 2 to display if a certain condition is fulfilled (e.g. if title = 'show two buttons'), how would we accomplish that?

>             generateNodeProps={rowInfo => ({
>               buttons: [
>                 <button
>                   onClick={() => doSomething()}
>                 >
>                   1
>                 </button>,
>                <button
>                   onClick={() => doSomething()}
>                 >
>                   2
>                 </button>
>                ],

**Comment by nreis11** [comment]
You can use the Inline If with Logical && Operator for this.
`  <SortableTree
          treeData={this.state.treeData}
          onChange={treeData => this.setState({ treeData })}
          generateNodeProps={rowInfo => ({
            buttons: [
              <button
                onClick={() => doSomething()}
              >
                1
            </button>,
              someCondition && <button
                onClick={() => doSomething()}
              >
                2
            </button>
            ]
          })
          }
        />`

**Comment by NickEmpetvee** [comment]
@nreis11 
Thank you. What would be the conditional syntax? I tried the below and it just inserted the string "treeIndex > 0" before the button.

...
```
        </button>,
          treeIndex > 0 && <button
            onClick={() => doSomething()}
          >
```
...

**Comment by NickEmpetvee** [comment]
From what I can tell, the issue is that after `buttons: [`, it is not accepting the suggested syntax. Any help is appreciated.

**Comment by NickEmpetvee** [comment]
This is resolved.  The below code works:

                treeIndex > 0 &&
                <button...>...</button>
Thanks @nreis11 .
