### ISSUE TITLE
Lazy loading is broken

### ISSUE THREAD

**Issue by wuweiweiwu** [frontend-collective/react-sortable-tree#369]
https://github.com/frontend-collective/react-sortable-tree/commit/c844c04b6248103ca42ae80e417679741c5607cd#r29717312

**Comment by HgAlexx** [comment]
Any chance to get this fixed ?

**Comment by wuweiweiwu** [comment]
@HgAlexx ill try to get to it asap but feel free to contribute

**Comment by HgAlexx** [comment]
It took some time but I find time to do the associated pull request: #461
