### ISSUE TITLE
Adding Dynamic icons in each node

### ISSUE THREAD

**Issue by nurul3101** [frontend-collective/react-sortable-tree#374]
I am trying to add icons in front of each node and based on whether node has children i want to change the icon. Also based on the expansion state i want to display different icons. 
In which method should i write my custom logic to achieve the goal?
I am currently using generateNodeProps method but i am not sure if it is possible to achieve it by adding props.

**Comment by wuweiweiwu** [comment]
Hi @nurul3101 I think a way you can do this is by using the [util functions](https://github.com/frontend-collective/react-sortable-tree#themes) to test each node to see if it has children etc.. And using `onChange` events to update the icons. 

hope that helps!

**Comment by nurul3101** [comment]
Hey @wuweiweiwu Thank you. I was able to add icons dynamically based on checking whether node has children.

**Comment by assafushy** [comment]
hi,

could you please give a snippet of how you changed the icon ?
