### ISSUE TITLE
loadLazyChildren error

### ISSUE THREAD

**Issue by chengchencc** [frontend-collective/react-sortable-tree#387]
# Reporting a Bug?

i try to use children lazy load refer to [Fix loadLazyChildren with children as function](https://github.com/frontend-collective/react-sortable-tree/pull/227) but not work.

i read the source code,find this change in react-sortable-tree.js(row number 150):
`  static getDerivedStateFromProps(nextProps, prevState) {
    const { instanceProps } = prevState;
    const newState = {};

    // make sure we have the most recent version of treeData
    instanceProps.treeData = nextProps.treeData;
    if (!isEqual(instanceProps.treeData, nextProps.treeData)) {
      if (instanceProps.ignoreOneTreeUpdate) {
        instanceProps.ignoreOneTreeUpdate = false;
      } else {
        newState.searchFocusTreeIndex = null;
        ReactSortableTree.loadLazyChildren(nextProps, prevState);
        Object.assign(
          newState,
          ReactSortableTree.search(nextProps, prevState, false, false, false)
        );
      }
`
`
instanceProps.treeData = nextProps.treeData;
if (!isEqual(instanceProps.treeData, nextProps.treeData)) 
`
this will be always equal. the code can not going into the if.

if this change cause bug?

**Comment by HgAlexx** [comment]
This is related to #369.
I've locally patched this doing a simple backup of _instanceProps.treeData_ before it is overwritten by _nextProps.treeData_ and using the backup for the _if (!isEqual(instanceProps.treeData, nextProps.treeData)) {_ test.
This fix is working fine for me, children are correctly lazyloaded on expanded again.

```
let prevTreeData = instanceProps.treeData;
// make sure we have the most recent version of treeData 
instanceProps.treeData = nextProps.treeData; 
if (!isEqual(prevTreeData, nextProps.treeData)) { 
```
