### ISSUE TITLE
two items in storybook codesanbox.io ERROR

### ISSUE THREAD

**Issue by huiman** [frontend-collective/react-sortable-tree#394]
Drag from external source
Drag out to remove

**Comment by lifejuggler** [comment]
I can't reproduce this in the https://frontend-collective.github.io/react-sortable-tree/storybook/?selectedKind=Basics&selectedStory=Minimal%20implementation&full=0&addons=0&stories=1&panelRight=0 and going to close this. Please resubmit the issue with screenshot and maybe link and way to reproduce the error you're seeing
