### ISSUE TITLE
Drag&Drop doesn`t work with NodeContentRenderer

### ISSUE THREAD

**Issue by psycura** [frontend-collective/react-sortable-tree#399]
# Reporting a Bug?

if i use `NodeContentRenderer` and as component use your `node-renderer-default.js`
On dragStart i receive an error in console:

> browser.js:38 Uncaught Error: Item must be an object.
>     at Object.invariant [as default] (browser.js:38)
>     at DragDropManagerImpl.beginDrag (dragDrop.js:54)
>     at Object.beginDrag (DragDropManagerImpl.js:43)
>     at HTML5Backend.webpackJsonp../node_modules/react-dnd-html5-backend/lib/HTML5Backend.js.HTML5Backend.handleTopDragStart (HTML5Backend.js:298)

However without `NodeContentRenderer` - everything work fine.
What can be a problem?

**Comment by psycura** [comment]
Ok, i found out that this problem is happen only when i pass `NodeContentRenderer` as props,
I just tried to import use your `src` folder and imported `ReactSortableTree` from there instead use of installed from `npm`. 
And if i import my `NodeContentRenderer` component directly to the `react-sortable-tree.js` and use it instead of ` import NodeRendererDefault from './node-renderer-default'`    everything work ,
So something broke behaviour of Drag&Drop when this custom `NodeContentRenderer` passed as props

**Comment by psycura** [comment]
Oh, i found what was a problem.
I passed `NodeContentRenderer` as `()=>< NodeContentRenderer/>` instead `{NodeContentRenderer}`
I think you should add some example with custom `NodeContentRenderer` to the examples.
Sorry, again

**Comment by mi1ami1a** [comment]
@psycura hey bro, could you share piece of your code please? i cant  understand how to use NodeContentRenderer

**Comment by Jantwel** [comment]
@psycura @mi1ami1a I think the problem is in using functional component as `nodeContentRenderer`. If you convert it to class everything is ok.

**Comment by mi1ami1a** [comment]
nodeContentRenderer={NodeRendererDefault} is work
