### ISSUE TITLE
New release with addNodeUnderParent option

### ISSUE THREAD

**Issue by shinework** [frontend-collective/react-sortable-tree#400]
Hey! Thanks for this great component 💜

Is it possible to ship a new release with the `addNodeUnderParent` new option (https://github.com/frontend-collective/react-sortable-tree/commit/ff980d8127e5839cd99425d385faf95289b5f83e) ? :shipit:

**Comment by marisev** [comment]
Could you please also update a typing for addNodeUnderParent to include this new option?

**Comment by dolezel** [comment]
Should be done
