### ISSUE TITLE
Can not rowHeight match just the height of the node's content?

### ISSUE THREAD

**Issue by YahngSungho** [frontend-collective/react-sortable-tree#406]
I wanted to dynamically adjust the height of the row to be equal to the height of the content of the node in the tree.

I looked at the code in the library and found that it was not possible with the original package. But I had not given up. And I had planned to modify the package personally. The original plan was to pass `ref` through the components, get the height from the `div` of the contents of the nodes, organize them into an object, and use that object's value in `rowHeight`.

It was a pretty big plan, but I thought it would be possible. Until I saw this part to pass the ref.

![learnobit c__users_user_learnobit - _anything jsx app - webstorm administrator 2018-09-29 22 39 17](https://user-images.githubusercontent.com/29212791/46246572-fad1c980-c43a-11e8-9eb4-725d9eec23eb.png)
![learnobit c__users_user_learnobit - _anything jsx app - webstorm administrator 2018-09-29 22 38 16](https://user-images.githubusercontent.com/29212791/46246574-fe655080-c43a-11e8-8d88-3ae60409c8c3.png)

Here, the `NodeContentRenderer` is the component returned by the HOC named `this.dndManager.wrapTarget()`. I must modify `dndManager` to pass `ref` here.
It was too much for me.

So I eventually gave up using Virtualized and adjusting the height. Instead, I assigned false to `isVirtualized` prop and modified the package a little bit.

![learnobit c__users_user_learnobit - _node_modules_react-sortable-tree_dist_index esm js - webstorm administrator 2018-09-29 22 48 13](https://user-images.githubusercontent.com/29212791/46246577-0a511280-c43b-11e8-8037-f9b6af41f128.png)

This works. By itself, the height of the node is adjusted to the height of the content. But I had to give up using Virtualized instead. I want to use it. Is there no way?

**Comment by YahngSungho** [comment]
I tried to edit [this file](https://github.com/frontend-collective/react-sortable-tree/blob/c83c2aae14d7d2e6c884da314b34a068bd4d9109/src/react-sortable-tree.js).

**Comment by gragland** [comment]
Can you somehow have a node detect when its height changes, pass up the new height that it reads from itself in a callback function, then update that node object to contain its new height? And then in`rowHeight` read it from the node object? No idea if that's doable, just an idea.

**Comment by YahngSungho** [comment]
I am thinking of a way of assigning a function instead of createRef() in ref as a way of solving this problem.
It's better to work on the parent component of SortableTree instead of modifying the package by adding a height value to node objects. Thanks for the hint, @gragland

**Comment by cobyrne09** [comment]
@YahngSungho do you recall if you were able to achieve this?
