### ISSUE TITLE
A strange part of the code

### ISSUE THREAD

**Issue by YahngSungho** [frontend-collective/react-sortable-tree#411]
![react-sortable-tree_react-sortable-tree js at master frontend-collective_react-sortable-tree - chrome 2018-10-16 23 40 36](https://user-images.githubusercontent.com/29212791/47078430-44ddec00-d23e-11e8-9e9a-b5931df691f3.png)

Now I am trying to understand this part of the code. What does this mean? If it does a shallow copy, it also gets the equality as the result of a deep comparison. isn't it? 

For your reference, this part is at lines 155-157 at https://github.com/frontend-collective/react-sortable-tree/blob/master/src/react-sortable-tree.js

**Comment by lifejuggler** [comment]
Is this still relevant?
