### ISSUE TITLE
Determine changes

### ISSUE THREAD

**Issue by florianbepunkt** [frontend-collective/react-sortable-tree#412]
# Requesting a Feature?

onChange returns the complete tree data. Is there a way to only get the actual changed bits of data? like a delta or diff? My use case is that I have a lot of items (sometimes only a few, sometime a few hundred), where each item is a different doc in our database. hence, I would like to only update thos docs, that were actually changed instead of all docs.

**Comment by nolandg** [comment]
Use the `onMoveNode` event. It gives you prevPath, nextPath, and currently moved node (and more). If your structure is a bunch of nested parent-children then moving a node should only modify the previous parent and all its immediate children and the new parent and all its immediate children. Use this event to update the prevParent by removing one of its children and updating all the indexes of the other children. Then update the nextParent by adding a child and changing all the nextParent's children's indexes. If children hold a reference to their parent, you'd also need to update that on the moved node.
