### ISSUE TITLE
replace `react-virtualized` with `react-tiny-virtual-list`?

### ISSUE THREAD

**Issue by redguardtoo** [frontend-collective/react-sortable-tree#414]
`react-virtualized` is too heavy weight (file size is more than 300Kb) while `react-tiny-virtual-list` is only 3Kb

**Comment by redguardtoo** [comment]
I checked the code. It's just one line `import { AutoSizer, List } from 'react-virtualized';` in `react-sortable-tree`.

I also read code of `AutoSizer` from `react-virtualized`. It's just simple function to get parent node size. I suggest writing a built in function to replace it. In the future, we could remove this function. It's not necessary to add `AutoSizer`, it's kind of over-engineering.

For `List`, `react-tiny-virtual-list` seems a better alternative. It's independent package and still actively maintained. It's only one component so the developer could focus on it's maintenance.

I could send you a pull request if you'd like to carry on?

**Comment by dolezel** [comment]
Send PR, I will check. Thanks

**Comment by af** [comment]
How does `react-tiny-virtual-list` compare with `react-window`? See #425

**Comment by wuweiweiwu** [comment]
react window is @bvaughn's rewrite of react virtualized. it exposes a slightly different api and is a bit more efficient

**Comment by wuweiweiwu** [comment]
as for react-tiny-virtual-list, ill have to take some time to dig into it

**Comment by wuweiweiwu** [comment]
haha I think it should work! We can pull in the `react-virtualized-autosizer` too

**Comment by wuweiweiwu** [comment]
closing in favor of #425
