### ISSUE TITLE
addNode Callback

### ISSUE THREAD

**Issue by pkhodaveissi** [frontend-collective/react-sortable-tree#419]
Hello

is there anyway I can get the path and other details of latest added node?
If there's a callback like `onMoveNode`, that would be great
tnx

**Comment by pkhodaveissi** [comment]
well, since there was no answer to this, I solved it as below,

i got the `treeIndex` from returned object value of addNodeUnderParent function call and then add it to the path of target node, result as you see is the path to new born element

**Comment by nahuelleiva** [comment]
@pkhodaveissi good day, sir.

Is quite old this issue and I know it's closed, but I'm looking for something like this. I need to extract the information from the node that was added recently to build an object and then persist it in a remote DB. Do you remember by any chance how did you manage to store the `treeIndex` from the returned object value of `addNodeUnderParent()`? That would give me an idea to build my functions.

Regards,
Nahuel
