### ISSUE TITLE
npm start command does not exist

### ISSUE THREAD

**Issue by Radu3000** [frontend-collective/react-sortable-tree#420]
I am new to react and this project.  Just tried to follow instructions.
1. Downloaded
2. Ran npm install successfully
3. Tried to run the following command and got this error:
C:\Projects\react-sortable-tree-master>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Radu\AppData\Roaming\npm-cache\_logs\2018-11-15T14_19_21_533Z-debug.log

**Comment by wuweiweiwu** [comment]
you can cd into the website `cd website`
