### ISSUE TITLE
how can i make nodes editable?

### ISSUE THREAD

**Issue by dhaval-lila** [frontend-collective/react-sortable-tree#454]
Hi , thanks for awesome package , I am currently working on project where node needs to editable by user and update that node in json and send it to back end . how can i achieve this using this module?

**Comment by lkoczorowski** [comment]
Check the storybook for a working example: https://frontend-collective.github.io/react-sortable-tree/storybook/?selectedKind=Basics&selectedStory=Modify%20nodes&full=0&addons=0&stories=1&panelRight=0

**Comment by Imaginativeone** [comment]
The storybook link is down. I'd like to get it back up, but I might need some guidance.

**Comment by lifejuggler** [comment]
@lkoczorowski , @Imaginativeone , @dhaval-lila  here is the working version of the storybook https://lifejuggler.github.io/react-sortable-tree/storybook

**Comment by pguardiario** [comment]
The updated link is down too now

**Comment by mohamedelhefni** [comment]
@pguardiario 
you can find the example here 
https://github.com/frontend-collective/react-sortable-tree/blob/master/stories/modify-nodes.js
