### ISSUE TITLE
SortableTreeWithoutDndContext renders nothing.

### ISSUE THREAD

**Issue by NiketMalik** [frontend-collective/react-sortable-tree#470]
# Bug

Sample Code Block:
```js
export default class App extends React.Component {
  render() {
    return (
      <div className="tree-wrapper">
        <SortableTree
          treeData={[
            {
              title: "`title`",
              subtitle: "`subtitle`",
              expanded: true,
              children: []
            }
          ]}
        />
      </div>
    );
  }
}
```

The above codeblock works when the default ***SortableTree*** is imported
```js
import SortableTree from "react-sortable-tree";
```

But renders nothing when ***SortableTreeWithoutDndContext*** is used
```js
import { SortableTreeWithoutDndContext as SortableTree } from "react-sortable-tree";
```

Codesandbox: https://codesandbox.io/s/4zv8yv6v6w

**Comment by serdaryesilmurat** [comment]
I have the same issue. Is anyone gonna fix this bug?

**Comment by dolezel** [comment]
Component needs `DragDropContext` from `react-dnd` to render. So if you do not provide it yourself, use default import.
If you are using `DragDropContext` yourself, check if it is put above SortableTree, not in different react subtree.

**Comment by NiketMalik** [comment]
@dolezel I do not want to use drag and drop context i.e `SortableTreeWithoutDndContext`, why do I need dnd package for that?

**Comment by dolezel** [comment]
Because that is the way how it works 🤷‍♂️
If you do not need DnD, there are lots of other implementations...

**Comment by NiketMalik** [comment]
@dolezel Can you give an example of those implementations. The actual issue which I'm facing is that my node contents a dropzone, and drag events are overridden by `SortableTree`

**Comment by dolezel** [comment]
https://reactjsexample.com/tag/tree/

**Comment by NiketMalik** [comment]
Oh you meant other libraries, I thought you meant other implementations of react-sortable-tree. Anyway thanks for the clarification.

**Comment by MoMoWongHK** [comment]
any update for this problem?

**Comment by fast0490f** [comment]
@MoMoWongHK Hi, use react-dnd@9.5.1
