### ISSUE TITLE
当节点高度不一致时，拖拽会出现预期位置错误的问题

### ISSUE THREAD

**Issue by xuxuzhang1994** [frontend-collective/react-sortable-tree#502]
# Reporting a Bug?

Please include either a failing unit test or a simple reproduction. You can start by forking the [CodeSandbox example](https://codesandbox.io/s/wkxvy3z15w)

# Requesting a Feature?

Provide as much information as possible about your requested feature. Here are a few questions you may consider answering:
* What's your use case? (Tell me about your application and what problem you're trying to solve.)
* What interface do you have in mind? (What new properties or methods do you think might be helpful?)
* Can you point to similar functionality with any existing libraries or components? (Working demos can be helpful.)

**Comment by xuxuzhang1994** [comment]
![image](https://user-images.githubusercontent.com/22954257/59750749-e035ce00-92b1-11e9-9539-6b50263f3f20.png)
![image](https://user-images.githubusercontent.com/22954257/59750828-065b6e00-92b2-11e9-8185-42545a3695d4.png)

**Comment by lifejuggler** [comment]
Can you convert the title to English please and would you be more descriptive of the problem? (ie is it a feature request or a bug?) Also an example would be great  if it is a bug and should be looked into

**Comment by lifejuggler** [comment]
closed because I don't understand this issue
