### ISSUE TITLE
How to remove case-sensitive searching?

### ISSUE THREAD

**Issue by 2503shubham** [frontend-collective/react-sortable-tree#508]
# Reporting a Bug?
It mot bug actually but need help with removing case sensitive in search query
Please include either a failing unit test or a simple reproduction. You can start by forking the [CodeSandbox example](https://codesandbox.io/s/wkxvy3z15w)

# Requesting a Feature?

Provide as much information as possible about your requested feature. Here are a few questions you may consider answering:
* What's your use case? (Tell me about your application and what problem you're trying to solve.)
* What interface do you have in mind? (What new properties or methods do you think might be helpful?)
* Can you point to similar functionality with any existing libraries or components? (Working demos can be helpful.)

**Comment by chase** [comment]
@2503shubham Change the searchMethod to your own implementation based on this: https://github.com/frontend-collective/react-sortable-tree/blob/master/src/utils/default-handlers.js#L47

**Comment by lifejuggler** [comment]
There is also a great example of how to do remove case-sensitive searching in the storybook(https://frontend-collective.github.io/react-sortable-tree/storybook/?selectedKind=Basics&selectedStory=Minimal%20implementation&full=0&addons=0&stories=1&panelRight=0) To see the code, please check here (https://github.com/frontend-collective/react-sortable-tree/blob/master/stories/search.js)

**Comment by 2503shubham** [comment]
@lifejuggler  @chase , Thanks for the help!  :)
