### ISSUE TITLE
How to change row style onClick?

### ISSUE THREAD

**Issue by 2503shubham** [frontend-collective/react-sortable-tree#509]
After clicking on any particular node, how can i change the color of that node(same like, when searched item the row gets highlighted)?

**Comment by t3db0t** [comment]
Replace your treeData structure with your own, mine is kind of stupid (`node.node.` etc)

```
<SortableTree
          treeData={this.state.treeData}
          onChange={treeData => this.setState({ treeData })}
          getNodeKey={node => node.node.id}
          generateNodeProps={node => {
            return {
              id:node.node.id,
              onClick: (e) => this.handleNodeClick(node, e),
// **** This is where the actual row gets rendered so do what you want with isSelected *****
              title: <div className={node.isSelected ? 'selected' : ''}>{node.node.title}</div>
            }
          }}
        />```

```
  handleNodeClick(node, e) {
    // ignore collapse/expand button
    const clickedItemClassName = e.target.className;
    if (
      clickedItemClassName === 'rstcustom__expandButton' ||
      clickedItemClassName === 'rstcustom__collapseButton'
    ) return;

    // set all items to correct isSelected value
    const newTree = map({
      treeData: this.state.treeData,
      getNodeKey: n => n.node.id,
      callback: n => {
        n.node.isSelected = (n.node.id === node.node.id);
        return n.node;
      },
      ignoreCollapsed: false
    });

    this.setState({ treeData: newTree });
  }
```

**Comment by lifejuggler** [comment]
This should've been asked in stackoverflow. Closing as it looks solved anyway
