### ISSUE TITLE
SortableTreeWithoutDndContext render null

### ISSUE THREAD

**Issue by whyang115** [frontend-collective/react-sortable-tree#511]
hi, i'm sorry for ask help.
when i use SortableTreeWithoutDndContext, there is nothing can be rendered, how can i fix it
![image](https://user-images.githubusercontent.com/23303376/61342701-b2768180-a87d-11e9-8c2a-8ac65569427f.png)

**Comment by deepakkadarivel** [comment]
<img width="577" alt="Screenshot 2019-07-22 at 1 14 12 PM" src="https://user-images.githubusercontent.com/14848432/61628462-ad04a700-ac82-11e9-990a-10976f060f1a.png">
I have the same issue.

**Comment by MadLord80** [comment]
I had the same problem.
I used:
"react": "^16.8.6"
"react-sortable-tree": "^2.6.2"

This wors for me:
use "react-dnd": "^7.3.0" and  "react-dnd-html5-backend": "^7.0.1"
then in script
```
import * as React from 'react'
import { SortableTreeWithoutDndContext as SortableTree  } from 'react-sortable-tree'
import { DragDropContext } from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'
import 'react-sortable-tree/style.css'

class TreeTest extends React.Component {
	constructor(props) {
		super(props)
		this.state = {
			treeData: [
				{ title: 'Chicken', children: [{ title: 'Egg' }] }
			]
		}
	}

	render() {
		return (
				<div style={{width: '100%'}}>
				<SortableTree
					isVirtualized={false}
					treeData={this.state.treeData}
					onChange={treeData => this.setState({treeData: [...treeData]})}
				/>
				</div>
		)
	}
}

const CTree = DragDropContext(HTML5Backend)(TreeTest)
export { CTree }
```

**Comment by noushad-pp** [comment]
I can confirm the same problem. It seems react-sortable-tree is incompatible with the latest versions of react-dnd. I was having the exact versions @MadLord80 has and it was working fine. I had to upgrade my dependencies lately with included react-dnd to 9.3.x and sortable-tree is not working anymore. it just renders null.

**Comment by Nauss** [comment]
@noushad-pp [comment](https://github.com/frontend-collective/react-sortable-tree/issues/511#issuecomment-533500260) works for me also.

I still have the react warnings from Draggable though...

**Comment by vivekmpuh** [comment]
i have tried downgrading  the version as mentioned in the above comments but nothing helped, do anyone have the fixed solution for this.

Thanks

**Comment by noushad-pp** [comment]
@vivekmpuh try using `resolutions` field in `package.json` to specify the exact versions of react-dnd and react-sortable-tree

**Comment by softwareplumber** [comment]
Same problem here, upgrade from 2.6.2 to 2.7 broke it, rollback fixed it. Don't think i've messed with the version of react-dnd.

**Comment by softwareplumber** [comment]
Is this related? https://github.com/react-dnd/react-dnd/issues/1257

**Comment by softwareplumber** [comment]
Maybe some of these problems due to react-dnd being a both a peer dependency at 7.3 and a hard dependency at 9.4?   

"dependencies": {
    "frontend-collective-react-dnd-scrollzone": "^1.0.2",
    "lodash.isequal": "^4.5.0",
    "prop-types": "^15.6.1",
    "react-dnd": "^9.4.0",
    "react-dnd-html5-backend": "^9.3.4",
    "react-lifecycles-compat": "^3.0.4",
    "react-virtualized": "^9.21.2"
  },
  "peerDependencies": {
    "react": "^16.3.0",
    "react-dnd": "^7.3.0",
    "react-dom": "^16.3.0"
  },
