### ISSUE TITLE
How to create a drop-down menu in react-sortable tree

### ISSUE THREAD

**Issue by suyog-pipliwaal** [frontend-collective/react-sortable-tree#517]
I have created a tree view using this library and I want to give a drop-down on each node with some functionality like create-child, remove-node, etc. I am able to do so using the separate button for each one but I want to give a button on which user click and a drop-down menu is a display with all the options mentions above. I have attached the screen-short.
![Screenshot from 2019-08-01 18-43-32](https://user-images.githubusercontent.com/24247201/62296936-c8935d00-b48d-11e9-8662-75528d88a398.png)
   Thanks in advance.

**Comment by Phenixer** [comment]
You can use **generateNodeProps** to add a button at the end.

```
generateNodeProps({ node }) {
    return {
        title: node.title,
        buttons: [(<button>Hi!</button>)],
    };
}
```

But this will be a simple _<button>_. If you need a dropdown, it's outside the scope of the react-sortable-tree, you might want to find a UX library.

**Comment by suyog-pipliwaal** [comment]
Thanks.
