### ISSUE TITLE
[Documentation] Styling Nodes

### ISSUE THREAD

**Issue by waynevanson** [frontend-collective/react-sortable-tree#521]
HI All,

This package is great in functionality, works out of the box! The iterator functions like `map()` are phenomenal! 

An ongoing issue I see for this component is styling. There's no guide or digestible information (especially newbies to this package, myself included) on **what** I can style and **how** to style it.

If anyone can shine some light on this, I'll be happy to contribute to some documentation with examples, pictures and diagrams.

**Questions:**
Are there special class names for each element?
At what point should I consider creating a theme instead of using CSS?

**Comment by suyog-pipliwaal** [comment]
I want to highlight a node when the mouse is over it. Can Somebody help!!!

**Comment by Phenixer** [comment]
> I want to highlight a node when the mouse is over it. Can Somebody help!!!

You can do `.rst__rowWrapper:hover .rst__rowContents { background-color: yellow; }`

From my little time with this package:
- You can change row height with **rowHeight**
- You can change the scaffold (lines showing hierarchy) width with **scaffoldBlockPxWidth**

What I did is put a style on the whole tree **className="mycustomclass"** and I used CSS to override the styles. Use Chrome/Firefox devtools (F12) to look at what the class names are. Things like **rst__rowWrapper**, **rst__moveHandle**, **rst__rowContents** etc...

Creating a theme requires to re-write the whole render so it's as a last resort (if styles aren't enough). You can't know if styles are enough for you unless you try, it would be difficult for them to list every possible scenarios where you would require a theme.

Additionally, you can overwrite the render of each item content with **generateNodeProps** prop. See [this](https://github.com/frontend-collective/react-sortable-tree/blob/master/stories/add-remove.js) example for instance.

I hope this helps!

**Comment by suyog-pipliwaal** [comment]
Thanks, I really appreciate the help.

**Comment by suyog-pipliwaal** [comment]
I want to highlight a particular node on which the user has Clicked. How can I do that? 
I was trying to do rst__row:focus {background-color:red} is not working.

**Comment by waynevanson** [comment]
Thank you for your response, it has clarified and confirmed information.

> Creating a theme requires to re-write the whole render so it's as a last resort (**if styles aren't enough**).

What if you don't work with styles, or prefer working with UI packages like MaterialIUI but need some flexibility? React is about creating components, which is putting all the relevant HTML, CSS and Javascript in a small reusable format for easy handling. Using CSS injection only is limiting and not really in line with the React workflow; not an API that feel native.

> rst__rowWrapper, rst__moveHandle, rst__rowContents etc...
I think these and the rest will have to be written in documentation. It's not really explained anywhere. Where would something like this go? My initial thought is in storybook in a section called styling.

Based on this discussion, it's assumed that styling is with CSS only and not with any UI packages.

I'm going to make a theme with the following API, to resolve what I see as limitations:
+ contents
+ the empty scaffolds
+ the current scaffold (holds the expand button)
+ row wrapper

They'd take props that a theme does and maybe some more, with dynamic typings included thanks to `ts-toolbelt` plugin.
This way it's flexible enough to add what you want without having to create a new theme.
