### ISSUE TITLE
Can we pass a function to handle onClick event

### ISSUE THREAD

**Issue by jinq102030** [frontend-collective/react-sortable-tree#525]
This is a question.

Wonder if it is possible to pass in a onclick handle function, which will be called with the title of the node that was clicked. 

Thanks in advance!

**Comment by nreis11** [comment]
I assume you're referring to handling any click within the node contents? I just created a quick example. You can create an onClick handler and pass it in the generateNodeProps prop.

https://codesandbox.io/embed/rstnodeclickhandler-81sew

**Comment by jinq102030** [comment]
Thanks @nreis11 for going out of your way and creating a working example!
