### ISSUE TITLE
Drag Preview Hides `rst__rowContents`

### ISSUE THREAD

**Issue by jeremyhicks** [frontend-collective/react-sortable-tree#526]
# Inconsistent behavior

[In the sandbox online](https://codesandbox.io/s/serene-matsumoto-npku7) it operates as I believe it should. Dragging the handle takes the handle and the content with it.

In my [example project](https://github.com/jeremyhicks/test-react-sortable-tree) which is a barebones `npx create-react-app test-sortable` app. Dragging the move handle there will hide the content.

See attached gifs in case this is an issue with building or other configuration outside of this project.

Running Codesandbox
![codesandbox](https://user-images.githubusercontent.com/1226024/63873892-4a838280-c975-11e9-8a17-497151de0794.gif)

Running Local
![local](https://user-images.githubusercontent.com/1226024/63873906-5111fa00-c975-11e9-8a5a-cc477589dcc6.gif)

**Comment by panda6412** [comment]
@jeremyhicks , I have faced the same issue, did you find the answer ?

**Comment by jeremyhicks** [comment]
@panda6412 sadly no. I just checked again today. In my project it all disappears. I'm not sure if it's this library or the underlying react-dnd-html5-backend. I had picked apart the code to try to get somewhere with it but had no luck.

**Comment by jeremyhicks** [comment]
The issue is gone in the latest update
