### ISSUE TITLE
Prevent identical names on same branch levels

### ISSUE THREAD

**Issue by mbelic** [frontend-collective/react-sortable-tree#528]
Hello, 
First of all, thank you on great component. I am using it to simulate creating of directory structure with folders and files.

I was wondering, before I tackle problem myself, if there is any method or recommended solution for problem of identical names on same branch levels (since that is how file system folders and files work).

I was thinking of using some of the props (canDrop on onMoveNode) to check whether or not that same branch already contains node with the same name. Similar as with changing the name of the already created node to something that is taken on that level.

Thank you for any suggestions you might have.

**Comment by nayan3d** [comment]
Hello @mbelic , did you get any solution for this ? 
I am also looking for similar solution to prevent duplicate names in the tree nodes.

**Comment by mbelic** [comment]
Hi @nayan3d 

I managed to overcome it by maintaining inside my state both regular tree structure and flat one. Check out **getFlatDataFromTree** for this one. 
By using and maintaining flat-tree data I was able to easily find source and target node (for creating new nodes and dragging existing ones) simply by using it's index value.

Dragging of the nodes went something like this:

`const canDrop = ({ node, prevPath, prevParent, prevTreeIndex, nextPath, nextParent, nextTreeIndex }) => {
// checking if we moved dragged node outside it's own parent
if (prevTreeIndex!==nextTreeIndex) {
				// storing new position in separate value
				let newInd = nextTreeIndex;
				// in case we are dragging upwards index must be lowered by one since apparently motion of the dragged node is already considered as changed
				if (nextTreeIndex<prevTreeIndex) {
					newInd = nextTreeIndex-1;
				}
				// picking up children from nodeData of current node from flat-tree by using index
				// I was keeping node data stringified previously when storing it in state hence need for JSON.parse
				if (JSON.parse(this.state.flatTree[newInd].nodeData).children) {
					// maping node names from children object and comparing it to current node.title
					if (JSON.parse(this.state.flatTree[newInd].nodeData).children.map((el) => {return el.title}).includes(node.title)) {
						return false;
					}
				}
			}

			return true;
		}`

Since creation of new nodes was handled by modal form I created that used validation form I won't go into detail about that, but it is similar method utilizing current node index (under which you want to create new node) and names of it's children. 

Hopefully this will help you in some way.
