### ISSUE TITLE
Question: why is canDrag not called for children nodes ? 

### ISSUE THREAD

**Issue by kohsah** [frontend-collective/react-sortable-tree#535]
Not sure if this is a bug or by design. I have a 3 level tree, and I want to prevent some nodes from being dragged based on attributes set on them. e.g. in the below image, I don't want "grouping" node to be draggable, but the others can be draggable

![image](https://user-images.githubusercontent.com/5685392/65849947-411d7980-e36a-11e9-8f19-af5560b97064.png)

Setting this prop on the tree does not work since it applies it only to the nodes at the parent level, and the `canDrag` callback is never called for the inner nodes.

`    canDrag={ (node) => node.node["type"] !== "grouping" }`

Am i missing something obvious ?

**Comment by GuyPaddock** [comment]
This is working for me... 

Here's my data structure:
```javascript
const data = [
  {
    type: 'artifact',
    title: 'My artifact title',
    expanded: true,
    children: [
      {
        type:  'asset',
        title: 'Asset 1',
      },
      {
        type:  'asset',
        title: 'Asset 2',
      },
    ]
  };
```

And my setup:
```jsx
  constructor(props) {
    super(props);

    this.state = {
      treeData: data,
    };
  }


  render() {
    return (
      <SortableTree
        isVirtualized={false}
        treeData={this.state.treeData}
        onChange={(treeData) => {
          this.setState({treeData});
        }}
        canNodeHaveChildren={(node) => (node.type === 'artifact')}
        canDrag={({node}) => (node.type === 'asset')}
        canDrop={({nextParent}) => (nextParent !== null) && (nextParent.type !== 'asset')}
      />
    );
  }
```

**Comment by kohsah** [comment]
Thank you @GuyPaddock ! i had not destructured the param for canDrag
