### ISSUE TITLE
v2.7.0 isn't published in npm

### ISSUE THREAD

**Issue by JonatanGarciaClavo** [frontend-collective/react-sortable-tree#540]
Well it isn't am issue at all, but I would like to know when it will be released v2.7.0 to npm. I saw master is updated and new tag was created, but it isn't in npm. This is needed to deal with problem of dnd contexts. So It will be awesome if you release it, because otherwise i can't use the lib :(

**Comment by JonatanGarciaClavo** [comment]
Also if there is something that block this, let me know and maybe i could help.

**Comment by Lumyo** [comment]
I  also would need this update.

**Comment by JonatanGarciaClavo** [comment]
At the end we did what it was mentioned in other issue. So provide context when it is used per library
