### ISSUE TITLE
style.css is missing !

### ISSUE THREAD

**Issue by AaronNGray** [frontend-collective/react-sortable-tree#574]
# Reporting a Bug?

 style.css is missing !

```
C:\Users\aaron\GitHub\AaronNGray\react-sortable-tree>yarn run build
yarn run v1.16.0
$ yarn run lint && yarn run clean
$ eslint src website

C:\Users\aaron\GitHub\AaronNGray\react-sortable-tree\website\index.js
  5:8  error  Unable to resolve path to module '../style.css'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)
```

**Comment by AaronNGray** [comment]
found out calling `rollup -c` builds style.css but its not called in the package scripts !

**Comment by AaronNGray** [comment]
Ah I understand this now you have to do a build before you do a prebuild !

**Comment by lifejuggler** [comment]
I have forked this project and made a fix for this along with a version bump on the dnd. Hopefully when the actual owners come back I can do a pull request to fix it but until then here is my package 📦 

https://github.com/lifejuggler/react-cat-tree
