### ISSUE TITLE
How to styling single nodes

### ISSUE THREAD

**Issue by abedalterra** [frontend-collective/react-sortable-tree#585]
Hi, I have some issues. I want to make the node that I click to have background color. I search in other issues, there's an answer to trigger click in generateNodeProps,
` <SortableTree
        canDrag={false}
        treeData={flows}
        onChange={treeData => onChangeDiagram(treeData)}
        generateNodeProps={({ node, path }) => ({
          onClick: () => {
            console.log(node);
          }
        })}
      />`

This is my SortableTree component, but I don't know how to change the background color of the clicked node. Do someone ever try that?

**Comment by Raja71** [comment]
<SortableTree
						treeData={this.state.treeData}
						onChange={this.treeData}
						onMoveNode={this.updateTreeData}
						generateNodeProps={rowInfo => ({
							onClick: () => {
								this.setState({ nodeInfo: rowInfo, status: true });
							},
							title: (
								<div className={this.state.status && rowInfo.node._id === this.state.nodeInfo.node._id ? "active-node" : ""}>
									{rowInfo.node.title}
								</div>
							)
						})}
					/>

**Comment by lifejuggler** [comment]
this looks resolved or no?
