### ISSUE TITLE
This demo has error ? some one got it...

### ISSUE THREAD

**Issue by VirgoArt** [frontend-collective/react-sortable-tree#599]

**Comment by mkamalkayani** [comment]
This is a working fork of the demo.
https://codesandbox.io/s/frontend-collectivereact-sortable-tree-sandbox-7nf1p

The imports were not working in the demo sandbox.

**Comment by jeremypeters** [comment]
@mkamalkayani  That fork is broken as well...

**Comment by MarcoFrasca** [comment]
New fork with working demo. The version of react-sortable-tree is 2.6.2, because 2.7.1 is broken. https://codesandbox.io/s/frontend-collectivereact-sortable-tree-sandbox-uipm4

**Comment by lifejuggler** [comment]
Not really a fix but thanks for the temporary solution. I am trying to get to the bottom of this error

**Comment by lifejuggler** [comment]
going to close this as there are other issues that I am tracking

**Comment by kmvan** [comment]
![image](https://user-images.githubusercontent.com/3839554/77224344-a165d900-6b9f-11ea-8ea5-e2e6c0d47de5.png)
