### ISSUE TITLE
How to find the parent node based on the current node? getNodeAtPath-way-of-working?

### ISSUE THREAD

**Issue by mariovde** [frontend-collective/react-sortable-tree#638]
Hi all,

Sorry, this is not really an issue, but I have been struggling with this for days now!
The problem is that I can't access the parent node, based on the current node.

Situation:
I have a tree like in this example: https://codesandbox.io/s/old-fog-djhd2
Create a child under the first node.
When that child is created, create a new (grand) child as a child under the first child.
Now you have a tree that goes 3 levels deep.
Click on the "update parent" button of the last child.
Check the console.

The console.log always returns null for the parentnode, when I expected to see the parent node info.

So, what's the correct way to use getNodeAtPath so that it actually returns something?
Or is there a better way to find the parent node of the node that's being deleted/clicked/...?

Thanks SO MUCH in advance!

**Comment by mariovde** [comment]
Ok, found my problem. I was passing treedata, path getnodekey as actual functional parameters instead of an object with those properties.

**Comment by fuzunspm** [comment]
could you please paste your solution?

**Comment by mariovde** [comment]
@fuzunspm what's your issue exactly?
maybe I could give you a more accurate solution

**Comment by mariovde** [comment]
@fuzunspm 

here's some code snippets that I used

<SortableTree
                    isVirtualized={false}
                    treeData={treeData} // state of the tree
                    canDrag={canDrag} // custom function to see if the node can be dragged
                    canDrop={canDrop} // custom function to see if the node can be dropped
                    canNodeHaveChildren={undefined}
                    onChange={onTreeChange} 
                    generateNodeProps={rowInfo => {
                        const isValid = rowInfo.node.hasOwnProperty("isValid")
                            ? rowInfo.node.isValid
                            : true;
                        return {
                            title: generateFieldType(rowInfo),
                            buttons: generateButtons(rowInfo), // this is where I use the whole parent logic, in generateButtons
                            className: !isValid ? "invalid" : "",
                        };
                    }}
                />


// geneateButtons

// 
const generateButtons = (rowInfo: *) => {
    const { node, path } = rowInfo;
    let getNodeKey = ({ treeIndex }) => treeIndex;
    const buttonArray = [];

    ...

    buttonArray.push(
        <Tooltip title="Delete node">
            <DeleteSweepOutlinedIcon
                fontSize="large"
                onClick={() => {
                    let getNodeKey = ({ treeIndex }) => treeIndex;

                    const newPath = [...path];
                    newPath.splice(-1, 1);
                    // newPath is the path of the parent, starting from the current node.

                    const parentNode = getNodeAtPath({
                        treeData,
                        path: newPath,
                        getNodeKey,
                    }).node;

                    console.log(parentNode)

                    ...
                   
                    parentNode.children = [];
                    treeData = { // ==> this treeData is a variable declared earlier in my code. 
                        treeData: changeNodeAtPath({
                            treeData,
                            path: newPath,
                            getNodeKey,
                            newNode: parentNode,
                        }),
                    };
            
                    ...


                    treeData = {
                        treeData: removeNodeAtPath({
                            treeData,
                            path,
                            getNodeKey,
                        }),
                    };
                            
                   ...

                }}
            />
        </Tooltip>,
    )
            }

**Comment by fuzunspm** [comment]
thank you! one last question. How can i map full path into treeData? I'm reading/sending treedata to server but i couldn't preserve order of items

**Comment by mariovde** [comment]
We don't have that issue, i think, in not preserving the order of items... so, I'm afraid I can't help you with that.

**Comment by Zach-Lu** [comment]
Unhandled Rejection (TypeError): Cannot read property 'node' of null。
U will get that error if u don't expand all nodes.
