### ISSUE TITLE
Unable to run the application in VS code or from the command prompt

### ISSUE THREAD

**Issue by msuresh551** [frontend-collective/react-sortable-tree#664]
# Reporting a Bug?

I have installed yarn and I am unable to run the code.
when I run the command like -> yarn start
$ parcel website/index.html
'parcel' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Please help me with how to run the application?

**Comment by HarunOr** [comment]
You need to install the node dependencies first.
If you are using yarn run the command `yarn install` first (alternatively with npm ` npm install`), then do `yarn start`.

**Comment by lifejuggler** [comment]
Feel like this is not really related to the package
