### ISSUE TITLE
`Cannot read property 'SOURCE' of undefined` in github page

### ISSUE THREAD

**Issue by alagos** [frontend-collective/react-sortable-tree#666]
I simply clicked [the link](https://frontend-collective.github.io/react-sortable-tree/) in the project's description and:

![Screen Shot 2020-02-17 at 9 15 52 AM](https://user-images.githubusercontent.com/475834/74612020-2e171480-5166-11ea-93be-1ba71aa63e0c.png)

**Comment by lolivia** [comment]
> I simply clicked [the link](https://frontend-collective.github.io/react-sortable-tree/) in the project's description and:
> 
> ![Screen Shot 2020-02-17 at 9 15 52 AM](https://user-images.githubusercontent.com/475834/74612020-2e171480-5166-11ea-93be-1ba71aa63e0c.png)

did you solve this issue?

**Comment by a7IadXE1c9** [comment]
Hey folks,
That bug still exists. When are you going to fix it?

**Comment by lifejuggler** [comment]
related to https://github.com/frontend-collective/react-sortable-tree/issues/673, and we are all busy people managing this on a volunteer basis @a7IadXE1c9. We welcome PRs so if you have a fix already make one, otherwise be patient.

**Comment by wuweiweiwu** [comment]
Ill try to find some time today

**Comment by wuweiweiwu** [comment]
closed with the new website!

https://frontend-collective.github.io/react-sortable-tree
