### ISSUE TITLE
Why "react-dnd" is in both "dependencies" and "peerDependencies"?

### ISSUE THREAD

**Issue by nikitaindik** [frontend-collective/react-sortable-tree#683]
Relevant parts of `package.json`:
```json
{
  "name": "react-sortable-tree",
  "version": "2.7.1",
  "dependencies": {
   ...
    "react-dnd": "^9.3.4"
  },
  "peerDependencies": {
    ...
    "react-dnd": "^7.3.0"
  },
  ...
}
```

As you can see "react-dnd" is specified in "dependencies" and "peerDependencies". Shouldn't it be either one or another?

This leads to unnecessary warning during package install.
`npm WARN react-sortable-tree@2.7.1 requires a peer of react-dnd@^7.3.0 but none is installed. You must install peer dependencies yourself.`

Should we remove "react-dnd" from "dependencies" or "peerDependencies"? Is there a reason for having both?

**Comment by zhaoxuyll** [comment]
This seems to be because peerDependencies of `frontend-collective-react-dnd-scrollzone@^1.0.2` caused. I think need keep the versions of both peerDependent packages at all times.
The current Yarn solution is on package.json add below code:
```json
  "resolutions": {
    ...
    "react-sortable-tree/react-dnd": "^9.3.4",
    "frontend-collective-react-dnd-scrollzone/react-dnd": "^7.3.0"
  }
```
