### ISSUE TITLE
Unable to start forked react-sortable-tree

### ISSUE THREAD

**Issue by gyurcigyurma** [frontend-collective/react-sortable-tree#706]
* Reporting a Bug?

bug

* What's your use case? (Tell me about your application and what problem you're trying to solve.)

After successfull installation when I try to start or build the forked project with `yarn start` or `yarn run build` it fails

```
$ yarn start

yarn run v1.22.4
$ parcel website/index.html
Server running at http://localhost:1234 
×  No entries found.
    at Bundler.bundle (C:\Users\Gyorgy\ProjectFiles\DataDict\react-sortable-tree\node_modules\parcel-bundler\src\Bundler.js:275:17)
    at async Bundler.serve (C:\Users\Gyorgy\ProjectFiles\DataDict\react-sortable-tree\node_modules\parcel-bundler\src\Bundler.js:842:7)
    at async Command.bundle (C:\Users\Gyorgy\ProjectFiles\DataDict\react-sortable-tree\node_modules\parcel-bundler\src\cli.js:241:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 
```

```
 yarn run build
yarn run v1.22.4
$ yarn run lint && yarn run clean
$ eslint src website

Oops! Something went wrong! :(

ESLint: 6.7.2.

No files matching the pattern "website" were found.
Please check for typing mistakes in the pattern.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I used the master branch. Is it something that I missed? The documentation is not too detailed unfortunately. 
Thank you!

**Comment by mike1011** [comment]
I am facing the same issue ..i dont know whether the changes are tested(adding `website` instead of `src`) or not but this is how i fixed few of the things...by updating the following...
```

in package.json

"start": "parcel ./src/index.js",
"lint": "eslint src",
```
and then `yarn run build` and `yarn start` works

**Comment by gyurcigyurma** [comment]
> 
> 
> I am facing the same issue ..i dont know whether the changes are tested(adding `website` instead of `src`) or not but this is how i fixed few of the things...by updating the following...
> 
> ```
> 
> in package.json
> 
> "start": "parcel ./src/index.js",
> "lint": "eslint src",
> ```
> 
> and then `yarn run build` and `yarn start` works

Thanks, I also figured out a solution:
Original code was:
`"prebuild": "yarn run lint && yarn run clean",`

Then I always faced eslint issues so just removed it:
`"prebuild": "yarn run clean"`

In the other hand when linking this repo with npm I got new and new errors. :(  This repo uses either rollup and parcel and I think it does not follow KISS principle. Thinking now to leave this and find/develop a new tree component. :(

**Comment by guldenmw** [comment]
It seems the following commit broke the scripts by removing the website directory. 

30749c74deba9b254c674bc0ded4fe2e6eb4cdce

@wuweiweiwu would you mind advising on how to solve this?

**Comment by lifejuggler** [comment]
I made my own fork of this and fixed the issue. 

my repo: https://github.com/lifejuggler/react-cat-tree

**Comment by wuweiweiwu** [comment]
@guldenmw will update!
