### ISSUE TITLE
How to collapse all/ expand all?

### ISSUE THREAD

**Issue by jaddoescad** [frontend-collective/react-sortable-tree#712]
is there a function that can be accessed that allows for expanding and collapsing all

**Comment by linusx** [comment]
Did you figure this out? Any solution?

**Comment by linusx** [comment]
BTW, I found a solution:

https://github.com/frontend-collective/react-sortable-tree/blob/f15d0d97ee8048c3084e05db9acf0d4797a872d6/src/examples/basicExample/app.js
