### ISSUE TITLE
react-sortable-tree in browser

### ISSUE THREAD

**Issue by claudius108** [frontend-collective/react-sortable-tree#713]
Hi,

This is a very nice piece of software that I would like to use in browser, but I am not yet able to generate the javascript files to use it.

Would someone be kind to share the needed files for me to run react-sortable-tree in browser or the commands needed to generate them?

Thanks,
Claudius

**Comment by mike1011** [comment]
Why dont you check the stories [here](https://github.com/frontend-collective/react-sortable-tree/tree/master/stories).

Moreover, you will need to [create a react-app](https://reactjs.org/docs/create-a-new-react-app.html) and then install this library and then use it as shown n the stories link above.

**Comment by claudius108** [comment]
Thank you, I will look at that.

Claudius

**Comment by lifejuggler** [comment]
There is also a storybook demo that you can also take a look at https://frontend-collective.github.io/react-sortable-tree/?path=/story/basics--minimal-implementation
