### ISSUE TITLE
"react-sortable-tree": "2.7.1"

### ISSUE THREAD

**Issue by zhaoxuyll** [frontend-collective/react-sortable-tree#735]
warning " > react-sortable-tree@2.7.1" has unmet peer dependency "react-dnd@^7.3.0".
warning "react-sortable-tree > frontend-collective-react-dnd-scrollzone@1.0.2" has incorrect peer dependency "react-dnd@^7.3.0".

**Comment by lifejuggler** [comment]
Can you provide some step in how you got to this error?

**Comment by zhaoxuyll** [comment]
> Can you provide some step in how you got to this error?

When run `yarn install` console show this error.
![image](https://user-images.githubusercontent.com/3224165/88762593-111a4f00-d1a4-11ea-83ba-1272050ebab8.png)

This is react-sortable-tree pacakge.json:
![image](https://user-images.githubusercontent.com/3224165/88763032-fc8a8680-d1a4-11ea-919a-9ffe33e1ae6d.png)

This is frontend-collective-react-dnd-scrollzone package.json:
![image](https://user-images.githubusercontent.com/3224165/88763167-43787c00-d1a5-11ea-9649-5a03510f23db.png)

But react-sorttable-tree package.json is dependencies "react-dnd": "^9.3.4":
![image](https://user-images.githubusercontent.com/3224165/88763247-66a32b80-d1a5-11ea-91ed-227d1274542d.png)

**Comment by andresmv94** [comment]
How you solved it?
