### ISSUE TITLE
Example Code required for the basic and advance features

### ISSUE THREAD

**Issue by gdhelp03** [frontend-collective/react-sortable-tree#778]
I am looking for example code for the latest features like button, search etc. Please provide the reference or example code to use your library.

with regards

**Comment by nreis11** [comment]
Are you talking about these? https://github.com/frontend-collective/react-sortable-tree/tree/master/stories
This is the code for the storybook examples.

**Comment by gdhelp03** [comment]
Thanks, I think, I got, what I want
