### ISSUE TITLE
Get treeIndex from addNodeUnderParent() function after adding a new node

### ISSUE THREAD

**Issue by nahuelleiva** [frontend-collective/react-sortable-tree#798]
Hello all.

Like the title says. The `addNodeUnderParent()` returns treeData and treeIndex after you add a node. I want to retrieve the treeIndex from the function after adding a new node on the tree. How is that possible?

Thanks in advance.

Regards,
Nahuel

**Comment by nreis11** [comment]
I'm going to borrow your code. Because the addNodeUnderParent() returns the treeData and treeIndex, you can just grab  it after creating the new object e.g. newTree.treeIndex

```javascript
handleClickOnItem(rowInfo) {
    const NEW_NODE = { 
         title: 'A', 
         needsTitle: true, 
         expanded: true, 
         children: [{ title: 'B' }, { title: 'C' }, { title: 'D' }] 
    };
    const newTree = addNodeUnderParent({
        treeData: this.state.treeData,
        newNode: NEW_NODE,
        expandParent: true,
        parentKey: rowInfo ? rowInfo.treeIndex : undefined,
        getNodeKey: ({ treeIndex }) => treeIndex,
    });
    const treeIndex = newTree.treeIndex;
    // Object destructuring
    const { treeIndex } = newTree;
}
```

**Comment by nahuelleiva** [comment]
@nreis11 thank you for your answer. Yes, this code I took it from another issue as a base and that was the moment when I realized I could do the same with my code, and the solution came from my own code haha sometimes you just have to step aside from what you are working to see the full picture.

Again, thank you for your answer!
Regards,
Nahuel
