### ISSUE TITLE
help

### ISSUE THREAD

**Issue by MarvenGong** [frontend-collective/react-sortable-tree#802]
# Reporting a Bug?

How can i get the source code of you demo at https://frontend-collective.github.io/react-sortable-tree/?path=/story/basics--add-and-remove-nodes-programmatically . please reply as soon as possible

**Comment by kayesn786** [comment]
Hi @MarvenGong ,
Please refer to this storybook link https://github.com/frontend-collective/react-sortable-tree/blob/master/stories/add-remove.js

**Comment by MarvenGong** [comment]
> Hi @MarvenGong ,
> Please refer to this storybook link https://github.com/frontend-collective/react-sortable-tree/blob/master/stories/add-remove.js

thanks a lot ,
