### ISSUE TITLE
[Question] Is it possible to edit the title node with onDoubleClick event?

### ISSUE THREAD

**Issue by nahuelleiva** [frontend-collective/react-sortable-tree#803]
I have displayed the node on the browser and whenever I double click on the title I want to be able to display an input to modify the title and store the change into a database. Is that possible?

Regards,
Nahuel

**Comment by nahuelleiva** [comment]
On a side note, I followed the idea from this issue #306 and I've managed to alter the title to show as an input.

I've modified an example from another issue and I've found that whenever the onClick event triggers, [every node will be rendered as input](https://codesandbox.io/s/rstnodeclickhandler-forked-vsmm5)

I tried to use `refs` on the input but without success. I cannot manage to edit just one node at the time.

**Comment by nreis11** [comment]
You need to add a conditional to check which node was clicked. If the node was clicked and it's in input mode, then render the form. Notice that I changed it to a positive conditional, which I think is more readable.

```javascript
// Line 69
title: this.state.isInput && node === this.state.nodeClicked ? <form>...</form> : node.title;
```

**Comment by nahuelleiva** [comment]
@nreis11 I don't believe in God but sure some god must bless you. I've spent hours trying to find a way to make this work and the solution was that simple. 

Thank you so much! I've modified my example with your suggestion and it properly works.
