### ISSUE TITLE
getTreeFromFlatData not respecting nodes order

### ISSUE THREAD

**Issue by nahuelleiva** [frontend-collective/react-sortable-tree#822]
Hi, everyone. @fritz-c @wuweiweiwu 

I have an issue where moving nodes at the same level are not correctly sorted after you've refreshed the browser, take this as an example, you have the following tree:

```javascript
-- parent
    |__ children_1
    |__ children_2
```
and let's say you move children_2 from its position, like this:
```javascript
-- parent
    |__ children_2
    |__ children_1
```
after moving the node, I'm able to record and update the node in the DB, but once I refresh the browser the tree is reverted back as it originally was, like this:
```javascript
-- parent
    |__ children_1
    |__ children_2
```
To load the tree I'm using the `getTreeFromFlatData` to transform the DB data into tree data.
I cannot get this working. Doesn't matter what I do, the sorting is never loaded correctly.

**Comment by absolutelysimon** [comment]
Can you put together a CodeSandbox example that shows the broken getTreeFromFlatData?

**Comment by cuicuiworld** [comment]
I have also encountered such problems. Have you solved them?

**Comment by nahuelleiva** [comment]
@absolutelysimon sorry for the late response, I was able to fix my problem and I don't remember too well how I did it. But I remember doing a 'hot load' just taking the treeIndex of the nodes from the updated tree and then reloading it again entirely with the new treeIndex structure. This helped me to load the tree in the correct way while maintaining the nodes' order in it in execution time. Very suboptimal solution but was the only thing I've found to make it work.

 @cuicuiworld I'll try to find the piece of code I made to showcase my solution but the above was the idea I came up with at that time.

**Comment by gokulprathin8** [comment]
any update on this @nahuelleiva ?

**Comment by nahuelleiva** [comment]
@gokulprathin8 hi, unfortunately, no. I can't share a code snippet on how I implemented this because I have no more access to the repo I've been working on. 

As far as I remember, the tree was sorting the elements by an internal `id` property that came up with each node while their treeIndex was correct, so each node should have its respective position after loading on the screen but this was not the case. So the idea I came up with at that time was to loop over the tree after it was done loading (this is after the `getTreeFromFlatData` function ended its execution), forcing the tree to sort the nodes by the `treeIndex` instead of this `id` property that was messing with my sorting.

Note that you'll have two sorting actions, one after the `getTreeFromFlatData` function ends and another one where you should sort the tree again by the `treeIndex` property. So it can be very suboptimal if you are working with big chunks of data. The library itself doesn't offer an alternative to this, maybe you can come up with a better solution for yourself.

Sorry for not being able to show a code snippet, I wish I could be more helpful but I hope this is clear enough for you to come up with a solution.

**Comment by gokulprathin8** [comment]
thankyou for the detailed information @nahuelleiva , I actually was storing the total tree after the change has occurred in the database, and retrieving the total tree JSON on page load. Your approach seems to be better than the one I currently have in place.
