### ISSUE TITLE
how can set first node not expand,  helper ~

### ISSUE THREAD

**Issue by xoptimal** [frontend-collective/react-sortable-tree#838]
How to set the first node without expansion function, move the whole to the left, align ~

**Comment by absolutelysimon** [comment]
Not sure what your question is. Are you asking how expand the first node in the tree?

**Comment by xoptimal** [comment]
What I want to say is whether the first node can not extend this function,
And it can't be dragged under the node, can it be realized?

@absolutelysimon

**Comment by absolutelysimon** [comment]
Hmmm, I don't understand what you're asking, sorry.
