### ISSUE TITLE
Failed to minify the code error

### ISSUE THREAD

**Issue by BolgarMaxym97** [frontend-collective/react-sortable-tree#933]
I use 2.8.0 version and when I make build got error:
**Failed to minify the code from this file:
        ./node_modules/@react-dnd/asap/dist/cjs/AsapQueue.js:6**
My dependencies:
       
        `  "dependencies": {
    "@humanscape/react-summernote-bs4": "^2.0.2",
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "autoprefixer": "7.1.6",
    "babel-core": "6.26.0",
    "babel-loader": "7.1.2",
    "babel-preset-react-app": "^3.1.1",
    "babel-runtime": "6.26.0",
    "bootstrap": "^4.3.1",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "1.1.3",
    "css-loader": "0.28.7",
    "dotenv": "4.0.0",
    "dotenv-expand": "4.2.0",
    "draft-js": "^0.11.7",
    "draftjs-to-html": "^0.9.1",
    "eslint": "4.10.0",
    "eslint-config-react-app": "^2.1.0",
    "eslint-loader": "1.9.0",
    "eslint-plugin-flowtype": "2.39.1",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-jsx-a11y": "5.1.1",
    "eslint-plugin-react": "7.4.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "file-saver": "^2.0.5",
    "font-awesome": "^4.7.0",
    "fs-extra": "3.0.1",
    "highcharts": "^9.1.0",
    "highcharts-react-official": "^3.0.0",
    "html-webpack-plugin": "2.29.0",
    "immutability-helper": "^3.0.1",
    "jquery": "^3.3.1",
    "match-sorter": "^2.3.0",
    "math-expression-evaluator": "^1.3.14",
    "medium-zoom": "^1.0.6",
    "moment": "^2.24.0",
    "nouislider-react": "^3.4.1",
    "object-assign": "4.1.1",
    "plotly.js": "^2.7.0",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.8",
    "promise": "8.0.1",
    "prop-types": "^15.7.2",
    "raf": "3.4.0",
    "react": "^16.8.2",
    "react-bootstrap-sweetalert": "^4.4.1",
    "react-color": "^2.17.0",
    "react-contextmenu": "^2.14.0",
    "react-cookies": "^0.1.0",
    "react-custom-scrollbars": "^4.2.1",
    "react-datepicker": "^3.8.0",
    "date-fns": "2.23.0",
    "react-datetime": "^2.16.3",
    "react-dev-utils": "^5.0.1",
    "react-dnd": "^9.3.4",
    "react-dnd-html5-backend": "^9.3.4",
    "react-dom": "^16.8.2",
    "react-draft-wysiwyg": "^1.14.7",
    "react-dropzone": "^11.3.2",
    "react-highcharts-no-data-to-display": "^1.0.2",
    "react-icons": "^3.11.0",
    "react-images-viewer": "^1.6.2",
    "react-input-range": "^1.3.0",
    "react-jvectormap": "0.0.16",
    "react-medium-image-zoom": "^4.3.4",
    "react-modal": "^3.8.1",
    "react-notifications-component": "^2.0.7",
    "react-plotly.js": "^2.5.1",
    "react-pro-sidebar": "^0.4.4",
    "react-router": "^4.3.1",
    "react-router-dom": "^5.1.2",
    "react-select": "^3.1.1",
    "react-select2-wrapper": "^1.0.4-beta6",
    "react-sortable-tree": "^2.8.0",
    "react-sortablejs": "6.0.0",
    "react-switch": "^7.0.0",
    "react-tag-autocomplete": "^6.1.0",
    "reactstrap": "^6.3.1",
    "resolve": "1.6.0",
    "sortablejs": "^1.14.0",
    "source-map-explorer": "^1.7.0",
    "style-loader": "0.19.0",
    "sw-precache-webpack-plugin": "0.11.4",
    "url-loader": "0.6.2",
    "validator": "^10.11.0",
    "webpack": "3.8.1",
    "webpack-dev-server": "2.9.4",
    "webpack-manifest-plugin": "1.3.2",
    "whatwg-fetch": "2.0.3",
    "why-did-you-update": "^1.0.6"
  },`

**Comment by LianBond** [comment]
Hi, getting the same issue, were you able to resolve this?
